// <auto-generated />
using System;
using BackendPTDetecta.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendPTDetecta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126200846_EsquemaFinalSeguros")]
    partial class EsquemaFinalSeguros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.HistorialClinico", b =>
                {
                    b.Property<int>("IdHistorialClinico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_HIS_CLINICA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialClinico"));

                    b.Property<string>("AlergiasPrincipales")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ALER_PRIN");

                    b.Property<string>("AntecedentesHereditarios")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ANTE_HEREDI");

                    b.Property<string>("EnfermedadesCronicas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ENFER_CRONI");

                    b.Property<string>("EstadoPacienteActual")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ESTADO_PACIEN");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ESTADO_REGISTRO");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_APER_HIS_CLIN");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_ELI");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_MOD");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_REG");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("TX_GRUP_SANG");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_PACIENTE");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_MOTIVO_ELI");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_ELI");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_MOD");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_REG");

                    b.HasKey("IdHistorialClinico");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("HISTORIAL_CLINICO");
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_PACIENTE");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_APE_PACIEN");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("TX_DIR_PACIEN");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("NU_DNI_PACIEN");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_EMAIL_PACIEN");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ESTADO_REGISTRO");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_ELI");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_MOD");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TX_FE_NAC_PACIEN");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_REG");

                    b.Property<int>("IdTipoSeguro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_TIPO_SEGURO");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_MOTIVO_ELI");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_NOM_PACIEN");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("TX_SEXO_PACIEN");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NU_TEL_PACIEN");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_ELI");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_MOD");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_REG");

                    b.HasKey("IdPaciente");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("IdTipoSeguro");

                    b.ToTable("PACIENTES");
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.TipoSeguro", b =>
                {
                    b.Property<int>("IdTipoSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_TIPO_SEGURO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoSeguro"));

                    b.Property<string>("CoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TX_CO_PAGO");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ESTADO_REGISTRO");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_ELI");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_MOD");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_REG");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_MOTIVO_ELI");

                    b.Property<string>("NombreSeguro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_NOM_SEG");

                    b.Property<string>("RucEmpresa")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("NU_RUC_EMPRESA");

                    b.Property<string>("TipoCobertura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_TIP_COBER");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_ELI");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_MOD");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_REG");

                    b.HasKey("IdTipoSeguro");

                    b.ToTable("TIPO_SEGUROS");

                    b.HasData(
                        new
                        {
                            IdTipoSeguro = 1,
                            CoPago = "0%",
                            EstadoRegistro = 1,
                            FechaRegistro = new DateTime(2025, 11, 26, 20, 8, 45, 726, DateTimeKind.Utc).AddTicks(7365),
                            NombreSeguro = "SIS",
                            RucEmpresa = "20100000001",
                            TipoCobertura = "Integral",
                            UsuarioRegistro = "SYSTEM"
                        },
                        new
                        {
                            IdTipoSeguro = 2,
                            CoPago = "0%",
                            EstadoRegistro = 1,
                            FechaRegistro = new DateTime(2025, 11, 26, 20, 8, 45, 726, DateTimeKind.Utc).AddTicks(7640),
                            NombreSeguro = "EsSalud",
                            RucEmpresa = "20500000002",
                            TipoCobertura = "Laboral",
                            UsuarioRegistro = "SYSTEM"
                        },
                        new
                        {
                            IdTipoSeguro = 3,
                            CoPago = "20%",
                            EstadoRegistro = 1,
                            FechaRegistro = new DateTime(2025, 11, 26, 20, 8, 45, 726, DateTimeKind.Utc).AddTicks(7642),
                            NombreSeguro = "EPS Pacifico",
                            RucEmpresa = "20600000003",
                            TipoCobertura = "Privada",
                            UsuarioRegistro = "SYSTEM"
                        });
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.HistorialClinico", b =>
                {
                    b.HasOne("BackendPTDetecta.Domain.Entities.Paciente", "Paciente")
                        .WithOne("HistorialClinico")
                        .HasForeignKey("BackendPTDetecta.Domain.Entities.HistorialClinico", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("BackendPTDetecta.Domain.Entities.TipoSeguro", "TipoSeguro")
                        .WithMany()
                        .HasForeignKey("IdTipoSeguro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoSeguro");
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("HistorialClinico");
                });
#pragma warning restore 612, 618
        }
    }
}
