// <auto-generated />
using System;
using BackendPTDetecta.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendPTDetecta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203163300_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.HistorialClinico", b =>
                {
                    b.Property<int>("IdHistorialClinico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_HIS_CLINICA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialClinico"));

                    b.Property<string>("AlergiasPrincipales")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ALER_PRIN");

                    b.Property<string>("AntecedentesHereditarios")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ANTE_HEREDI");

                    b.Property<string>("CodigoHistoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TX_CODIGO_HISTORIA");

                    b.Property<string>("EnfermedadesCronicas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ENFER_CRONI");

                    b.Property<string>("EstadoPacienteActual")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ESTADO_PACIEN");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ESTADO_REGISTRO");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FE_APERTURA");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FE_ELI");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FE_MOD");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FE_REG");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("TX_GRUP_SANG");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_PACIENTE");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_MOTIVO_ELI");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_ELI");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_MOD");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_REG");

                    b.HasKey("IdHistorialClinico");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("HISTORIAS_CLINICAS");
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_PACIENTE");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_APE_PACIEN");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("TX_CODIGO_PACIENTE")
                        .HasComputedColumnSql("'P' || LPAD(\"NU_ID_PACIENTE\"::TEXT, 5, '0')", true);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("TX_DIR_PACIEN");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NU_DNI_PACIEN");

                    b.Property<int>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("NU_EDAD_PACIEN");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_EMAIL_PACIEN");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ESTADO_REGISTRO");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FE_ELI");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FE_MOD");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("TX_FE_NAC_PACIEN");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FE_REG");

                    b.Property<int?>("IdHistoriaClinica")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_HIS_CLINICA");

                    b.Property<int?>("IdTipoSeguro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_TIPO_SEGURO");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_MOTIVO_ELI");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_NOM_PACIEN");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("TX_SEXO_PACIEN");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NU_TEL_PACIEN");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_ELI");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_MOD");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_REG");

                    b.HasKey("IdPaciente");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("IdTipoSeguro");

                    b.ToTable("PACIENTES");
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.TipoSeguro", b =>
                {
                    b.Property<int>("IdTipoSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_TIPO_SEGURO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoSeguro"));

                    b.Property<string>("CoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TX_CO_PAGO");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ESTADO_REGISTRO");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FE_ELI");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FE_MOD");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FE_REG");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_MOTIVO_ELI");

                    b.Property<string>("NombreSeguro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_NOM_SEG");

                    b.Property<string>("RucEmpresa")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("NU_RUC_EMPRESA");

                    b.Property<string>("TipoCobertura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_TIP_COBER");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_ELI");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_MOD");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_REG");

                    b.HasKey("IdTipoSeguro");

                    b.ToTable("TIPO_SEGUROS");

                    b.HasData(
                        new
                        {
                            IdTipoSeguro = 1,
                            CoPago = "0%",
                            EstadoRegistro = 1,
                            FechaRegistro = new DateTime(2025, 12, 3, 16, 32, 59, 689, DateTimeKind.Utc).AddTicks(4955),
                            NombreSeguro = "SIS",
                            RucEmpresa = "20100000001",
                            TipoCobertura = "Integral",
                            UsuarioRegistro = "SYSTEM"
                        },
                        new
                        {
                            IdTipoSeguro = 2,
                            CoPago = "0%",
                            EstadoRegistro = 1,
                            FechaRegistro = new DateTime(2025, 12, 3, 16, 32, 59, 689, DateTimeKind.Utc).AddTicks(5172),
                            NombreSeguro = "EsSalud",
                            RucEmpresa = "20500000002",
                            TipoCobertura = "Laboral",
                            UsuarioRegistro = "SYSTEM"
                        },
                        new
                        {
                            IdTipoSeguro = 3,
                            CoPago = "20%",
                            EstadoRegistro = 1,
                            FechaRegistro = new DateTime(2025, 12, 3, 16, 32, 59, 689, DateTimeKind.Utc).AddTicks(5175),
                            NombreSeguro = "EPS Pacifico",
                            RucEmpresa = "20600000003",
                            TipoCobertura = "Privada",
                            UsuarioRegistro = "SYSTEM"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.HistorialClinico", b =>
                {
                    b.HasOne("BackendPTDetecta.Domain.Entities.Paciente", "Paciente")
                        .WithOne("HistorialClinico")
                        .HasForeignKey("BackendPTDetecta.Domain.Entities.HistorialClinico", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("BackendPTDetecta.Domain.Entities.TipoSeguro", "TipoSeguro")
                        .WithMany()
                        .HasForeignKey("IdTipoSeguro");

                    b.Navigation("TipoSeguro");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("HistorialClinico");
                });
#pragma warning restore 612, 618
        }
    }
}
