// <auto-generated />
using System;
using BackendPTDetecta.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendPTDetecta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.HistoriaClinica", b =>
                {
                    b.Property<int>("IdHistoriaClinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_HIS_CLINICA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistoriaClinica"));

                    b.Property<string>("CodigoHistoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TX_CODIGO_HISTORIA");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ESTADO_REGISTRO");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_APERTURA");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_ELI");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_MOD");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_REG");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_MOTIVO_ELI");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_ELI");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_MOD");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_REG");

                    b.HasKey("IdHistoriaClinica");

                    b.ToTable("HISTORIAS_CLINICAS");
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_PACIENTE");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_APE_PACIEN");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NU_DNI_PACIEN");

                    b.Property<int>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("NU_EDAD_PACIEN");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ESTADO_REGISTRO");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_ELI");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_MOD");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TX_FE_NAC_PACIEN");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_REG");

                    b.Property<int?>("IdHistoriaClinica")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_HIS_CLINICA");

                    b.Property<int?>("IdTipoSeguro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_TIPO_SEGURO");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_MOTIVO_ELI");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_NOM_PACIEN");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("TX_SEXO_PACIEN");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_ELI");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_MOD");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_REG");

                    b.HasKey("IdPaciente");

                    b.HasIndex("IdHistoriaClinica");

                    b.HasIndex("IdTipoSeguro");

                    b.ToTable("PACIENTES");
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.TipoSeguro", b =>
                {
                    b.Property<int>("IdTipoSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NU_ID_TIPO_SEGURO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoSeguro"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("TX_DESCRIPCION");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("NU_ESTADO_REGISTRO");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_ELI");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_MOD");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FE_REG");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_MOTIVO_ELI");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TX_NOMBRE_SEGURO");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_ELI");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_MOD");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ID_USU_REG");

                    b.HasKey("IdTipoSeguro");

                    b.ToTable("TIPOS_SEGURO");

                    b.HasData(
                        new
                        {
                            IdTipoSeguro = 1,
                            EstadoRegistro = 1,
                            FechaRegistro = new DateTime(2025, 11, 26, 17, 48, 16, 47, DateTimeKind.Utc).AddTicks(3944),
                            Nombre = "SIS",
                            UsuarioRegistro = "SYSTEM"
                        },
                        new
                        {
                            IdTipoSeguro = 2,
                            EstadoRegistro = 1,
                            FechaRegistro = new DateTime(2025, 11, 26, 17, 48, 16, 47, DateTimeKind.Utc).AddTicks(4212),
                            Nombre = "EsSalud",
                            UsuarioRegistro = "SYSTEM"
                        },
                        new
                        {
                            IdTipoSeguro = 3,
                            EstadoRegistro = 1,
                            FechaRegistro = new DateTime(2025, 11, 26, 17, 48, 16, 47, DateTimeKind.Utc).AddTicks(4214),
                            Nombre = "Privado",
                            UsuarioRegistro = "SYSTEM"
                        });
                });

            modelBuilder.Entity("BackendPTDetecta.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("BackendPTDetecta.Domain.Entities.HistoriaClinica", "HistoriaClinica")
                        .WithMany()
                        .HasForeignKey("IdHistoriaClinica");

                    b.HasOne("BackendPTDetecta.Domain.Entities.TipoSeguro", "TipoSeguro")
                        .WithMany()
                        .HasForeignKey("IdTipoSeguro");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("TipoSeguro");
                });
#pragma warning restore 612, 618
        }
    }
}
